@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(-msep-data patches) for ARM/elf
	.file	"swap.c"
.gcc2_compiled.:
	.section .rodata
	.align	2
.LC0:
	.ascii	"a=%d, b=%d\012\000"
.text
	.align	2
	.global	main
	.type	 main,function
main:
	@ args = 0, pretend = 0, frame = 12
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #12
	bl	__gccmain
	mov	r3, #972
	add	r3, r3, #1
	str	r3, [fp, #-16]
	mov	r3, #136
	str	r3, [fp, #-20]
	ldr	r3, [fp, #-16]
	str	r3, [fp, #-24]
	ldr	r3, [fp, #-20]
	str	r3, [fp, #-16]
	ldr	r3, [fp, #-24]
	str	r3, [fp, #-20]
	ldr	r0, .L4
	ldr	r1, [fp, #-16]
	ldr	r2, [fp, #-20]
	bl	printf
	b	.L3
.L5:
	.align	2
.L4:
	.word	.LC0
.L3:
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 main,.Lfe1-main
