@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(-msep-data patches) for ARM/elf
	.file	"sum.c"
.gcc2_compiled.:
.text
	.align	2
	.global	sum
	.type	 sum,function
sum:
	@ args = 0, pretend = 0, frame = 12
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #12
	str	r0, [fp, #-16]
	mov	r3, #0
	str	r3, [fp, #-20]
	mov	r3, #1
	str	r3, [fp, #-24]
.L3:
	ldr	r3, [fp, #-24]
	ldr	r2, [fp, #-16]
	cmp	r3, r2
	ble	.L6
	b	.L4
.L6:
	ldr	r3, [fp, #-20]
	ldr	r2, [fp, #-24]
	add	r3, r3, r2
	str	r3, [fp, #-20]
.L5:
	ldr	r3, [fp, #-24]
	add	r2, r3, #1
	str	r2, [fp, #-24]
	b	.L3
.L4:
	ldr	r3, [fp, #-20]
	mov	r0, r3
	b	.L2
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 sum,.Lfe1-sum
